using System;
using System.Collections.Generic;

#nullable disable

namespace Reporting.WebApi.Models.DbModels
{
    public partial class TmpParamValue
    {
        public string SPar1 { get; set; }
        public string SPar2 { get; set; }
        public string SPar3 { get; set; }
        public string SPar4 { get; set; }
        public string SPar5 { get; set; }
        public string SPar6 { get; set; }
        public string SPar7 { get; set; }
        public string SPar8 { get; set; }
        public string SPar9 { get; set; }
        public string SPar10 { get; set; }
        public string SPar11 { get; set; }
        public string SPar12 { get; set; }
        public string SPar13 { get; set; }
        public string SPar14 { get; set; }
        public string SPar15 { get; set; }
        public string SPar16 { get; set; }
        public string SPar17 { get; set; }
        public string SPar18 { get; set; }
        public string SPar19 { get; set; }
        public string SPar20 { get; set; }
        public decimal? NPar1 { get; set; }
        public decimal? NPar2 { get; set; }
        public decimal? NPar3 { get; set; }
        public decimal? NPar4 { get; set; }
        public decimal? NPar5 { get; set; }
        public decimal? NPar6 { get; set; }
        public decimal? NPar7 { get; set; }
        public decimal? NPar8 { get; set; }
        public decimal? NPar9 { get; set; }
        public decimal? NPar10 { get; set; }
        public decimal? NPar11 { get; set; }
        public decimal? NPar12 { get; set; }
        public decimal? NPar13 { get; set; }
        public decimal? NPar14 { get; set; }
        public decimal? NPar15 { get; set; }
        public decimal? NPar16 { get; set; }
        public decimal? NPar17 { get; set; }
        public decimal? NPar18 { get; set; }
        public decimal? NPar19 { get; set; }
        public decimal? NPar20 { get; set; }
        public string UserName { get; set; }
        public int? RowNum { get; set; }
        public Guid? ParamId1 { get; set; }
        public Guid? ParamId2 { get; set; }
        public Guid? ParamId3 { get; set; }
        public Guid? ParamId4 { get; set; }
        public Guid? ParamId5 { get; set; }
        public Guid? ParamId6 { get; set; }
        public Guid? ParamId7 { get; set; }
        public Guid? ParamId8 { get; set; }
        public Guid? ParamId9 { get; set; }
        public Guid? ParamId10 { get; set; }
        public Guid? ParamId11 { get; set; }
        public Guid? ParamId13 { get; set; }
        public Guid? ParamId14 { get; set; }
        public Guid? ParamId16 { get; set; }
        public Guid? ParamId17 { get; set; }
        public Guid? ParamId18 { get; set; }
        public Guid? ParamId19 { get; set; }
        public Guid? ParamId20 { get; set; }
        public Guid? ValueId1 { get; set; }
        public Guid? ValueId2 { get; set; }
        public Guid? ValueId3 { get; set; }
        public Guid? ValueId4 { get; set; }
        public Guid? ValueId5 { get; set; }
        public Guid? ValueId6 { get; set; }
        public Guid? ValueId7 { get; set; }
        public Guid? ValueId8 { get; set; }
        public Guid? ValueId9 { get; set; }
        public Guid? ValueId10 { get; set; }
        public Guid? ValueId11 { get; set; }
        public Guid? ValueId12 { get; set; }
        public Guid? ValueId13 { get; set; }
        public Guid? ValueId14 { get; set; }
        public Guid? ValueId15 { get; set; }
        public Guid? ValueId16 { get; set; }
        public Guid? ValueId17 { get; set; }
        public Guid? ValueId18 { get; set; }
        public Guid? ValueId19 { get; set; }
        public Guid? ValueId20 { get; set; }
        public int? DataType1 { get; set; }
        public int? DataType2 { get; set; }
        public int? DataType3 { get; set; }
        public int? DataType4 { get; set; }
        public int? DataType5 { get; set; }
        public int? DataType6 { get; set; }
        public int? DataType7 { get; set; }
        public int? DataType8 { get; set; }
        public int? DataType9 { get; set; }
        public int? DataType10 { get; set; }
        public int? DataType11 { get; set; }
        public int? DataType12 { get; set; }
        public int? DataType13 { get; set; }
        public int? DataType14 { get; set; }
        public int? DataType15 { get; set; }
        public int? DataType16 { get; set; }
        public int? DataType17 { get; set; }
        public int? DataType18 { get; set; }
        public int? DataType19 { get; set; }
        public int? DataType20 { get; set; }
        public Guid? ProcessId { get; set; }
        public Guid? ParamId12 { get; set; }
        public Guid? WorkId { get; set; }
        public string UnitName { get; set; }
        public Guid? ParamId15 { get; set; }
        public int? CalculateType1 { get; set; }
        public int? CalculateType2 { get; set; }
        public int? CalculateType3 { get; set; }
        public int? CalculateType4 { get; set; }
        public int? CalculateType5 { get; set; }
        public int? CalculateType6 { get; set; }
        public int? CalculateType7 { get; set; }
        public int? CalculateType8 { get; set; }
        public int? CalculateType9 { get; set; }
        public int? CalculateType10 { get; set; }
        public int? CalculateType11 { get; set; }
        public int? CalculateType12 { get; set; }
        public int? CalculateType13 { get; set; }
        public int? CalculateType14 { get; set; }
        public int? CalculateType15 { get; set; }
        public int? CalculateType16 { get; set; }
        public int? CalculateType17 { get; set; }
        public int? CalculateType18 { get; set; }
        public int? CalculateType19 { get; set; }
        public int? CalculateType20 { get; set; }
        public int? LinkNum1 { get; set; }
        public int? LinkNum2 { get; set; }
        public int? LinkNum3 { get; set; }
        public int? LinkNum4 { get; set; }
        public int? LinkNum5 { get; set; }
        public int? LinkNum6 { get; set; }
        public int? LinkNum7 { get; set; }
        public int? LinkNum8 { get; set; }
        public int? LinkNum9 { get; set; }
        public int? LinkNum10 { get; set; }
        public int? LinkNum11 { get; set; }
        public int? LinkNum12 { get; set; }
        public int? LinkNum13 { get; set; }
        public int? LinkNum14 { get; set; }
        public int? LinkNum15 { get; set; }
        public int? LinkNum16 { get; set; }
        public int? LinkNum17 { get; set; }
        public int? LinkNum18 { get; set; }
        public int? LinkNum19 { get; set; }
        public string LinkText1 { get; set; }
        public string LinkText2 { get; set; }
        public string LinkText3 { get; set; }
        public string LinkText4 { get; set; }
        public string LinkText5 { get; set; }
        public string LinkText6 { get; set; }
        public string LinkText8 { get; set; }
        public string LinkText9 { get; set; }
        public string LinkText10 { get; set; }
        public string LinkText11 { get; set; }
        public string LinkText12 { get; set; }
        public string LinkText13 { get; set; }
        public string LinkText14 { get; set; }
        public string LinkText15 { get; set; }
        public string LinkText16 { get; set; }
        public string LinkText17 { get; set; }
        public string LinkText18 { get; set; }
        public string LinkText19 { get; set; }
        public string LinkText20 { get; set; }
        public string LinkText7 { get; set; }
        public Guid? DictionaryValueId1 { get; set; }
        public Guid? DictionaryValueId2 { get; set; }
        public Guid? DictionaryValueId3 { get; set; }
        public Guid? DictionaryValueId4 { get; set; }
        public Guid? DictionaryValueId5 { get; set; }
        public Guid? DictionaryValueId6 { get; set; }
        public Guid? DictionaryValueId7 { get; set; }
        public Guid? DictionaryValueId8 { get; set; }
        public Guid? DictionaryValueId9 { get; set; }
        public Guid? DictionaryValueId10 { get; set; }
        public Guid? DictionaryValueId11 { get; set; }
        public Guid? DictionaryValueId12 { get; set; }
        public Guid? DictionaryValueId13 { get; set; }
        public Guid? DictionaryValueId14 { get; set; }
        public Guid? DictionaryValueId15 { get; set; }
        public Guid? DictionaryValueId16 { get; set; }
        public Guid? DictionaryValueId17 { get; set; }
        public Guid? DictionaryValueId18 { get; set; }
        public Guid? DictionaryValueId19 { get; set; }
        public Guid? DictionaryValueId20 { get; set; }
        public int? LinkType1 { get; set; }
        public int? LinkType2 { get; set; }
        public int? LinkType3 { get; set; }
        public int? LinkType4 { get; set; }
        public int? LinkType5 { get; set; }
        public int? LinkType6 { get; set; }
        public int? LinkType7 { get; set; }
        public int? LinkType8 { get; set; }
        public int? LinkType9 { get; set; }
        public int? LinkType10 { get; set; }
        public int? LinkType11 { get; set; }
        public int? LinkType12 { get; set; }
        public int? LinkType13 { get; set; }
        public int? LinkType14 { get; set; }
        public int? LinkType15 { get; set; }
        public int? LinkType16 { get; set; }
        public int? LinkType17 { get; set; }
        public int? LinkType18 { get; set; }
        public int? LinkType19 { get; set; }
        public int? LinkType20 { get; set; }
        public decimal? NPar21 { get; set; }
        public decimal? NPar22 { get; set; }
        public decimal? NPar23 { get; set; }
        public decimal? NPar24 { get; set; }
        public decimal? NPar25 { get; set; }
        public decimal? NPar26 { get; set; }
        public decimal? NPar27 { get; set; }
        public decimal? NPar28 { get; set; }
        public decimal? NPar29 { get; set; }
        public decimal? NPar30 { get; set; }
        public int? LinkNum20 { get; set; }
    }
}
